### PR TITLE
Add Maghead PHP ORM benchmark testsuite

### PR DESCRIPTION
**Pull request by c9s**
Thanks for writing the benchmark test suites!

Added TestSuite for Maghead ORM: https://github.com/maghead/maghead

### CODE REVIEW

**Comment by c9s** [comment]
Here is my result with php 7.1

```
|-------------------------------------------------------------------------------------------------------|
| Library                          | Insert | findPk | complex| hydrate|  with  | memory usage |  time  |
| --------------------------------:| ------:| ------:| ------:| ------:| ------:| ------------:| ------:|
|                              PDO |     40 |      4 |     12 |     74 |    181 |    1,699,136 |   0.32 |
|                                  |        |        |        |        |        |              |        |
|                          Maghead |     96 |      0 |     56 |     85 |    213 |    8,388,608 |   0.47 |
|                                  |        |        |        |        |        |              |        |
|                           LessQL |     93 |     20 |    290 |    124 |    142 |    7,990,728 |   0.68 |
|                                  |        |        |        |        |        |              |        |
|                             YiiM |    160 |     20 |    317 |    115 |    340 |    6,291,456 |   0.97 |
|                    YiiMWithCache |    178 |     23 |    337 |    106 |    315 |    6,291,456 |   0.97 |
|                                  |        |        |        |        |        |              |        |
|                            Yii2M |    299 |     49 |    292 |    152 |    293 |    6,291,456 |   1.12 |
|                Yii2MArrayHydrate |    307 |     43 |    284 |    102 |    270 |    6,291,456 |   1.02 |
|               Yii2MScalarHydrate |    297 |     39 |    274 |     92 |    155 |    6,291,456 |   0.88 |
|                                  |        |        |        |        |        |              |        |
|                         Propel20 |    141 |     19 |    376 |    283 |    386 |    8,388,608 |   1.22 |
|                Propel20WithCache |    108 |      9 |    330 |    235 |    322 |    8,388,608 |   1.01 |
|           Propel20FormatOnDemand |    103 |      9 |    333 |    215 |    315 |    8,388,608 |   0.98 |
|                                  |        |        |        |        |        |              |        |
|                        DoctrineM |    167 |     47 |    283 |    225 |    223 |   18,874,368 |   1.05 |
|               DoctrineMWithCache |    166 |     38 |    298 |    276 |    246 |   18,874,368 |   1.07 |
|            DoctrineMArrayHydrate |    173 |     38 |    282 |    137 |    156 |   16,777,216 |   0.84 |
|           DoctrineMScalarHydrate |    162 |     40 |    279 |    122 |    129 |   16,777,216 |   0.77 |
|          DoctrineMWithoutProxies |    172 |     41 |    280 |    164 |    311 |   16,777,216 |   1.02 |
|                                  |        |        |        |        |        |              |        |
|                         Eloquent |    323 |     47 |    343 |    145 |    274 |    8,388,608 |   1.16 |
|             EloquentWithoutEvent |    288 |     46 |    346 |    151 |    263 |    8,388,608 |   1.11 |
|-------------------------------------------------------------------------------------------------------|
```

**Comment by Big-Shark** [comment]
big thx

**Comment by c9s** [comment]
@Big-Shark would you mind if I send another PR to update the results?

**Comment by Big-Shark** [comment]
@c9s nope, I am waiting your PR

**Comment by c9s** [comment]
Hi @Big-Shark  thanks, I've sent the PR #5. please take a look.

**Pull request merged**
